### ISSUE TITLE
v1 roadmap

### ISSUE THREAD

**Issue by foodtooth** [foodtooth/express-starter#1]
- [x] i18n
- [x] swagger for API Docs
- [x] jsdoc
- [x] jwt for token based authentication
- [ ] oauth
- [x] eslint
- [x] `debug` for development
- [x] `winston` for multi-transport logging
- [x] `config` for importing-configuration
- [ ] test coverage (istanbul)
- [x] unit test (mocha, chai)
- [ ] integration test ()
- [ ] functional test (Puppeteer)
- [x] `pm2` for process management, and monitor
- [x] ~~use `nodemon` (for simplicity and explicitly)~~
- [ ] ~~gitlab-ci for CI/CD~~
- [ ] try the integration with travis ci
- [ ] docker for container
- [ ] ~~use mongodb nodejs driver instead of mongoose~~
- [x] use mongoose as node mongodb odm
- [ ] some orm for sql (sequelize)
- [ ] tools for server monitor (For development, cpu profiling, disk space)
- [x] heapdump and memwatch for memory watching
- [ ] tools for application monitor (For development, database connection, network connection)
